### PR TITLE
Fix/services icons

### PR DESCRIPTION
**Pull request by nourneme**
Hey @pixelstrici can you take a look and make sure i got this services icon code in the right spots please?

### CODE REVIEW

**Review by ptyx11 — CHANGES_REQUESTED** [review]
The icons look low resolution. On mobile and desktop

**Comment by ptyx11** [comment]
@nourneme

**Comment by pixelstrici** [comment]
@nourneme I suggest that you export the files in SVG for the sharpest possible result.

**Comment by ptyx11** [comment]
the same goes for the nav bar on mobile. it looks pixelated.

**Pull request merged**
